### ISSUE TITLE
Refs are url encoded after bundling

### ISSUE THREAD

**Issue by lzap** [sourcemeta/jsonschema#246]
Hello, I have the following documents:

```yaml
# blueprint2.schema.yaml
---
"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://github.com/osbuild/blueprint-schema/blueprint2
type: object
required:
- name
properties:
  cacerts:
    oneOf:
    - description: Certs
      type: array
      items:
        "$ref": "https://github.com/osbuild/blueprint-schema/ca_cert"
    - type: 'null'
```

...and...

```yaml
# ca_cert.schema.yaml
---
"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://github.com/osbuild/blueprint-schema/ca_cert
type: object
required:
- cert
properties:
  cert:
    description: The PEM-encoded certificate.
    type: string
additionalProperties: false
```

I run the bundle command:

```
jsonschema bundle schema/blueprint2.schema.yaml --verbose --resolve schema/ --extension schema.yaml --without-id
```

But for some reason, the `$ref` value is URL encoded or has some wrong characters in it: `#/$defs/https%3A~1~1github.com~1osbuild~1blueprint-schema~1ca_cert`

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "cacerts": {
      "oneOf": [
        {
          "description": "Certs",
          "type": "array",
          "items": {
            "$ref": "#/$defs/https%3A~1~1github.com~1osbuild~1blueprint-schema~1ca_cert"
          }
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "$defs": {
    "https://github.com/osbuild/blueprint-schema/ca_cert": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "required": [
        "cert"
      ],
      "properties": {
        "cert": {
          "description": "The PEM-encoded certificate.",
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}
```

Chances are I am doing it wrong, but filing an issue just for the case.
